@extends('app')
@section('content')
<style>
.prod-board{background:#fff;padding:18px;color:#171717}.prod-filters{display:grid;grid-template-columns:.8fr 1fr 1fr 1.1fr .9fr 1.2fr;gap:8px;align-items:end}.prod-label{display:block;text-align:center;font-size:.78rem;font-weight:700;margin-bottom:5px}.prod-board .form-select,.prod-board .form-control{border-radius:0;border-color:#ddd;font-size:.75rem}.prod-dates{display:flex;gap:8px;margin:12px 0;max-width:310px}.prod-cards{display:grid;grid-template-columns:1.25fr 1.25fr 1.25fr 1.25fr;gap:8px}.prod-card,.prod-chart-card{border:1.5px solid #202020;border-radius:10px;background:#fff;padding:12px}.prod-card{text-align:center;min-height:96px}.prod-value{font-size:1.45rem;font-weight:500}.prod-muted{color:#777;font-size:.78rem}.prod-progress{display:flex;height:18px;margin-top:8px}.prod-progress span{color:#fff;font-size:.7rem}.prod-progress .yes{background:#d8bc45}.prod-progress .no{background:#333}.prod-chart-card{margin-top:10px}.prod-bottom{display:grid;grid-template-columns:1fr 1fr;gap:10px}.prod-board.loading{opacity:.58;pointer-events:none}@media(max-width:991px){.prod-filters,.prod-cards,.prod-bottom{grid-template-columns:1fr 1fr}}@media(max-width:575px){.prod-filters,.prod-cards,.prod-bottom{grid-template-columns:1fr}}
</style>
<div class="main-content"><div class="page-content"><div class="container-fluid"><div class="card border-0 shadow-sm"><div class="card-body prod-board" id="prodBoard">
<div class="prod-filters">
<div><span class="prod-label">Sistema</span><select class="form-select" disabled><option>Real</option></select></div>
<div><label class="prod-label" for="prodCategoria">Tipo de venta</label><select id="prodCategoria" class="form-select prod-filter"><option value="tradicional">Tradicional</option><option value="no_tradicional">No tradicional</option></select></div>
<div><label class="prod-label" for="prodGrupo">Grupo</label><select id="prodGrupo" class="form-select prod-filter"><option value="">Todas</option>@foreach($filtros['grupos'] as $i)<option value="{{ $i }}">{{ $i }}</option>@endforeach</select></div>
<div><label class="prod-label" for="prodCentral">Central/Ruta</label><select id="prodCentral" class="form-select prod-filter"><option value="">Todas</option>@foreach($filtros['centrales'] as $i)<option value="{{ $i }}">{{ $i }}</option>@endforeach</select></div>
<div><label class="prod-label" for="prodGerente">Gerente</label><select id="prodGerente" class="form-select prod-filter"><option value="">Todos</option>@foreach($filtros['gerentes'] as $i)<option value="{{ $i }}">{{ $i }}</option>@endforeach</select></div>
<div><label class="prod-label" for="prodTerminal">Terminales</label><select id="prodTerminal" class="form-select prod-filter"><option value="">Terminal</option>@foreach($filtros['terminales'] as $i)<option value="{{ $i }}">{{ $i }}</option>@endforeach</select></div>
</div>
<div class="prod-dates"><input type="date" id="prodDesde" class="form-control prod-filter" value="{{ $ultimaFecha }}"><input type="date" id="prodHasta" class="form-control prod-filter" value="{{ $ultimaFecha }}"></div>
<div class="prod-cards"><div class="prod-card"><div class="prod-value" id="prodActivas">0</div><div class="prod-muted">Terminales activas</div><div class="prod-progress"><span class="yes" id="prodYes" style="width:0%"></span><span class="no" id="prodNo" style="width:100%"></span></div></div><div class="prod-card"><div class="prod-value" id="prodVentas">$0</div><div class="prod-muted">Ventas</div></div><div class="prod-card"><div class="prod-value" id="prodVariacion">—</div><div class="prod-muted">Variación mes actual / mes pasado</div></div><div class="prod-card"><div class="prod-value" id="prodPromedio">$0</div><div class="prod-muted">Promedio por día (mes actual)</div></div></div>
<div class="prod-chart-card"><div id="prodDailyChart"></div></div><div class="prod-bottom"><div class="prod-chart-card"><div id="prodPieChart"></div></div><div></div></div>
</div></div></div></div></div></div>
<script src="{{ asset('libs/apexcharts/apexcharts.min.js') }}"></script>
<script>document.addEventListener('DOMContentLoaded',function(){const board=document.getElementById('prodBoard'),money=v=>`$${new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Number(v||0))}`;let daily=null,pie=null;function render(d){prodActivas.textContent=d.terminales.activas;prodVentas.textContent=money(d.ventas);prodPromedio.textContent=money(d.promedio_dia);prodVariacion.textContent=d.variacion_mes===null?'—':`${d.variacion_mes>=0?'▲':'▼'} ${Math.abs(d.variacion_mes).toFixed(1)}%`;const pct=d.terminales.activas?d.terminales.vendieron/d.terminales.activas*100:0;prodYes.style.width=`${pct}%`;prodYes.textContent=`${d.terminales.vendieron} ${pct.toFixed(0)}%`;prodNo.style.width=`${100-pct}%`;prodNo.textContent=`${d.terminales.sin_ventas} ${(100-pct).toFixed(0)}%`;if(daily)daily.destroy();if(pie)pie.destroy();daily=new ApexCharts(document.querySelector('#prodDailyChart'),{chart:{type:'line',height:300,toolbar:{show:false}},series:[{name:'Ventas',type:'column',data:d.grafico.map(x=>x.total)},{name:'Variación',type:'line',data:d.grafico.map(x=>x.variacion)}],xaxis:{categories:d.grafico.map(x=>x.dia)},yaxis:[{labels:{formatter:v=>money(v)}},{opposite:true,labels:{formatter:v=>`${v.toFixed(0)}%`}}],colors:['#e4cf6d','#222'],dataLabels:{enabled:true,enabledOnSeries:[0],formatter:v=>money(v),style:{colors:['#111']}},stroke:{width:[0,2]},legend:{position:'top'}});daily.render();pie=new ApexCharts(document.querySelector('#prodPieChart'),{chart:{type:'donut',height:290},series:d.productos.map(x=>Number(x.total)),labels:d.productos.map(x=>x.producto),colors:['#e4cf6d','#222','#bfa646','#777','#f0df92','#444','#d5c15c','#999','#eadb85','#666'],legend:{position:'right'},dataLabels:{enabled:true,formatter:(v,o)=>`${o.w.globals.labels[o.seriesIndex]} ${v.toFixed(1)}%`}});pie.render()}async function load(){const p=new URLSearchParams({fecha_desde:prodDesde.value,fecha_hasta:prodHasta.value,categoria:prodCategoria.value,grupo:prodGrupo.value,central:prodCentral.value,gerente:prodGerente.value,terminal:prodTerminal.value});board.classList.add('loading');try{const r=await fetch(`{{ route('bi.lotobet-real.productos-data') }}?${p}`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('No fue posible consultar productos.');render(await r.json())}catch(e){Swal.fire('Error',e.message,'error')}finally{board.classList.remove('loading')}}document.querySelectorAll('.prod-filter').forEach(x=>x.addEventListener('change',load));load()});</script>
@endsection
