<?php

return [
    [
        'nombre' => 'Nuevos ingresos',
        'descripcion' => 'Consulta empleados activos con menos de 20 días hábiles desde su fecha de ingreso.',
        'url' => '/recursos-humanos/nuevos-ingresos',
        'icono' => 'ri-user-add-line',
        'categoria' => 'Personal',
        'tags' => ['nuevos ingresos', 'empleados', 'fecha de ingreso', 'días hábiles'],
        'activo' => true,
    ],
    [
        'nombre' => 'Movimiento de usuario',
        'descripcion' => 'Registra el traslado manual de empleados entre terminales, centros de costo o grupos.',
        'url' => '/recursos-humanos/movimiento-usuario',
        'icono' => 'ri-user-shared-line',
        'categoria' => 'Control',
        'tags' => ['movimiento', 'usuario', 'empleado', 'terminal', 'centro de costo', 'grupo'],
        'activo' => true,
    ],
    [
        'nombre' => 'Agencias sin actividad',
        'descripcion' => 'Identifica agencias activas con ventas en cero o sin registros y permite documentar el motivo.',
        'url' => '/recursos-humanos/agencias-sin-actividad',
        'icono' => 'ri-store-2-line',
        'categoria' => 'Control',
        'tags' => ['agencias', 'ventas', 'actividad', 'central', 'gerente'],
        'activo' => true,
    ],
    [
        'nombre' => 'Cruce de Usuarios',
        'descripcion' => 'Cruza usuarios de ventas con la maestra de empleados y detecta diferencias.',
        'url' => '/recursos-humanos/cruce-usuarios',
        'icono' => 'ri-arrow-left-right-line',
        'categoria' => 'Control',
        'tags' => ['cruce', 'usuarios', 'empleados', 'lotobet', 'lotedom'],
        'activo' => true,
    ],
    [
        'nombre' => 'Reporte de faltantes',
        'descripcion' => 'Consulta faltantes por empleado, sistema y agencia con alertas configurables.',
        'url' => '/recursos-humanos/faltantes',
        'icono' => 'ri-error-warning-line',
        'categoria' => 'Control',
        'tags' => ['faltantes', 'empleados', 'alertas', 'lotobet', 'lotedom'],
        'activo' => true,
    ],
    [
        'nombre' => 'Solicitudes de Empleo',
        'descripcion' => 'Gestiona solicitudes, formularios y expedientes de candidatos.',
        'url' => '/registro-empleados',
        'icono' => 'ri-file-user-line',
        'categoria' => 'Reclutamiento',
        'tags' => ['solicitudes', 'registro', 'candidatos', 'empleo'],
        'activo' => true,
    ],
    [
        'nombre' => 'Empleados',
        'descripcion' => 'Consulta empleados, estatus, dashboard y masa salarial por empresa.',
        'url' => '/empleados',
        'icono' => 'ri-team-line',
        'categoria' => 'Personal',
        'tags' => ['empleados', 'dashboard', 'estatus', 'salarios'],
        'activo' => true,
    ],
    [
        'nombre' => 'Novedades de Horario',
        'descripcion' => 'Revisa novedades, marcas y variaciones de horario del personal.',
        'url' => '/recursos-humanos/novedades-horario',
        'icono' => 'ri-time-line',
        'categoria' => 'Asistencia',
        'tags' => ['horario', 'novedades', 'asistencia', 'marcas'],
        'activo' => true,
    ],
    [
        'nombre' => 'Entrevista Online',
        'descripcion' => 'Registra entrevistas telefónicas u online realizadas a candidatos.',
        'url' => '/entrevistas-online',
        'icono' => 'ri-video-chat-line',
        'categoria' => 'Reclutamiento',
        'tags' => ['entrevista', 'candidatos', 'vacantes', 'online'],
        // Vista ocultada del hub de Recursos Humanos; las rutas se conservan para no perder historial ni datos.
        'activo' => false,
    ],
    [
        'nombre' => 'Empleados No Regularizados',
        'descripcion' => 'Da seguimiento a empleados pendientes de regularización.',
        'url' => '/empleados-no-regularizados',
        'icono' => 'ri-user-warning-line',
        'categoria' => 'Control',
        'tags' => ['regularizados', 'pendientes', 'empleados'],
        'activo' => false,
    ],
    [
        'nombre' => 'Ventas Sin Empleado',
        'descripcion' => 'Identifica ventas que necesitan asociación o validación de empleado.',
        'url' => '/ventas-sin-empleado',
        'icono' => 'ri-user-search-line',
        'categoria' => 'Control',
        'tags' => ['ventas', 'sin empleado', 'cédula', 'validación'],
        'activo' => false,
    ],
];
